#
# Table structure for table 'tx_jscontactform_domain_model_contactform'
#
CREATE TABLE tx_jscontactform_domain_model_contactform (

	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,

	name varchar(255) DEFAULT '' NOT NULL,
	gender varchar(255) DEFAULT '' NOT NULL,
	first_name varchar(255) DEFAULT '' NOT NULL,
	middle_name varchar(255) DEFAULT '' NOT NULL,
	last_name varchar(255) DEFAULT '' NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	birthday date DEFAULT '0000-00-00',
	email varchar(255) DEFAULT '' NOT NULL,
	phone varchar(255) DEFAULT '' NOT NULL,
	fax varchar(255) DEFAULT '' NOT NULL,
	mobile varchar(255) DEFAULT '' NOT NULL,
	www varchar(255) DEFAULT '' NOT NULL,
	address text NOT NULL,
	building varchar(255) DEFAULT '' NOT NULL,
	room varchar(255) DEFAULT '' NOT NULL,
	city varchar(255) DEFAULT '' NOT NULL,
	zip varchar(255) DEFAULT '' NOT NULL,
	region varchar(255) DEFAULT '' NOT NULL,
	country varchar(255) DEFAULT '' NOT NULL,
	company varchar(255) DEFAULT '' NOT NULL,
	position varchar(255) DEFAULT '' NOT NULL,
	image int(11) unsigned NOT NULL default '0',
	message text NOT NULL,
	description text NOT NULL,
	skype varchar(255) DEFAULT '' NOT NULL,
	twitter varchar(255) DEFAULT '' NOT NULL,
	facebook varchar(255) DEFAULT '' NOT NULL,
	linkedin varchar(255) DEFAULT '' NOT NULL,
	creation_date int(11) DEFAULT '0' NOT NULL,
	receiver_email_configuration tinyint(1) unsigned DEFAULT '0' NOT NULL,
	receiver_email_sent tinyint(1) unsigned DEFAULT '0' NOT NULL,
	receiver_name text NOT NULL,
	receiver_email text NOT NULL,
	receiver_sender_name varchar(255) DEFAULT '' NOT NULL,
	receiver_sender_email varchar(255) DEFAULT '' NOT NULL,
	receiver_noreply_name varchar(255) DEFAULT '' NOT NULL,
	receiver_noreply_email varchar(255) DEFAULT '' NOT NULL,
	receiver_cc_send tinyint(1) unsigned DEFAULT '0' NOT NULL,
	receiver_cc_name varchar(255) DEFAULT '' NOT NULL,
	receiver_cc_email varchar(255) DEFAULT '' NOT NULL,
	receiver_bcc_send tinyint(1) unsigned DEFAULT '0' NOT NULL,
	receiver_bcc_name varchar(255) DEFAULT '' NOT NULL,
	receiver_bcc_email varchar(255) DEFAULT '' NOT NULL,
	receiver_email_subject text NOT NULL,
	receiver_email_body text NOT NULL,
	user_email_configuration tinyint(1) unsigned DEFAULT '0' NOT NULL,
	user_email_sent tinyint(1) unsigned DEFAULT '0' NOT NULL,
	user_sender_name varchar(255) DEFAULT '' NOT NULL,
	user_sender_email varchar(255) DEFAULT '' NOT NULL,
	user_noreply_name varchar(255) DEFAULT '' NOT NULL,
	user_noreply_email varchar(255) DEFAULT '' NOT NULL,
	user_cc_send tinyint(1) unsigned DEFAULT '0' NOT NULL,
	user_cc_name varchar(255) DEFAULT '' NOT NULL,
	user_cc_email varchar(255) DEFAULT '' NOT NULL,
	user_bcc_send tinyint(1) unsigned DEFAULT '0' NOT NULL,
	user_bcc_name varchar(255) DEFAULT '' NOT NULL,
	user_bcc_email varchar(255) DEFAULT '' NOT NULL,
	user_email_subject text NOT NULL,
	user_email_body text NOT NULL,
	feuser varchar(255) DEFAULT '' NOT NULL,
	ip varchar(255) DEFAULT '' NOT NULL,
	useragent text NOT NULL,
	visitors_country varchar(255) DEFAULT '' NOT NULL,
	referer_domain varchar(255) DEFAULT '' NOT NULL,
	referer_uri text NOT NULL,
	page varchar(255) DEFAULT '' NOT NULL,
	mobile_device tinyint(1) unsigned DEFAULT '0' NOT NULL,
	website_language varchar(255) DEFAULT '' NOT NULL,
	website_language_id varchar(255) DEFAULT '' NOT NULL,
	browser_language varchar(255) DEFAULT '' NOT NULL,

	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	crdate int(11) unsigned DEFAULT '0' NOT NULL,
	cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	starttime int(11) unsigned DEFAULT '0' NOT NULL,
	endtime int(11) unsigned DEFAULT '0' NOT NULL,

	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(255) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage int(11) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
	t3ver_move_id int(11) DEFAULT '0' NOT NULL,

	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumblob,

	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY t3ver_oid (t3ver_oid,t3ver_wsid),
 KEY language (l10n_parent,sys_language_uid)

);

## EXTENSION BUILDER DEFAULTS END TOKEN - Everything BEFORE this line is overwritten with the defaults of the extension builder